
if (!requireNamespace("BiocManager"))
    install.packages("BiocManager", repos="http://cran.cnr.berkeley.edu")
BiocManager::install()
BiocManager::install(c("DESeq2","gplots","ggplot2", "PoiClaClu","ggfortify","geneplotter","hexbin","vsn", "pheatmap","fission","org.Hs.eg.db"))
BiocManager::install(c("scater","scran","R.utils","yaml","ensembldb","EnsDb.Hsapiens.v79","EnsDb.Mmusculus.v79","RGBL"))
BiocManager::install("edgeR")
BiocManager::install("Rtsne")
BiocManager::install("apeglm")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("org.Mm.eg.db")
